parameters:
#    quorra_core.example.class: Quorra\CoreBundle\Example

services:
#    quorra_core.example:
#        class: %quorra_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
