imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

#doctrine mongod
doctrine_mongodb:
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: Quorra
    document_managers:
        default:
            auto_mapping: true
 
fos_user:
    db_driver: mongodb # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Quorra\CoreBundle\Document\User            

fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
      alias:  facebook
      app_id: 380608795298616
      secret: 7343986bd08ee295ab84be6c1859da2d
      cookie: true
      permissions: [email, user_birthday, user_location]

services:
    fos.facebook.user:
        class: Quorra\CoreBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"

#fos_twitter:
#   file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
#    consumer_key: q7cBvc3r4DoSEAGBty9g
#    consumer_secret: 0h8MW4qA7OtBn9fLXgFasrBw1ju7F0rAj3IuDTOv4
#    callback_url: http://inversia.com/login_check

#services:
#  fos.twitter.user:
#    class: Inversia\CoreBundle\Security\User\Provider\TwitterProvider
#    arguments:
#      twitter_oauth: "@fos_twitter.api"
#      userManager: "@fos_user.user_manager"
#      validator: "@validator"
#      session: "@session"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
