QuorraCoreBundle:
    resource: "@QuorraCoreBundle/Resources/config/routing.yml"
    prefix:   /

#application/config/routing.yml
_security_check:
    pattern:  /login_check
_security_logout:
    pattern:  /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
